include theme.conf

font_size 11
shell_integration no-cursor
confirm_os_window_close 0
cursor_shape block
cursor_trail 40
cursor_trail_decay 0.25 0.65
cursor_trail_start_threshold 10 10
cursor_trail_color none
window_padding_width 15
modify_font cell_height 115%

tab_bar_style fade
tab_bar_edge top
tab_bar_margin_width 0
tab_bar_margin_height 0 0
tab_bar_min_tabs 2
tab_separator ""
active_tab_font_style normal
inactive_tab_font_style normal

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_window_with_cwd
