palette = 0 = #29292f
palette = 1 = #ffb4ab
palette = 2 = #bcc2ff
palette = 3 = #e7bad6
palette = 4 = #c4c5dd
palette = 5 = #dfe0ff
palette = 6 = #e0e0f9
palette = 7 = #c7c5d0
palette = 8 = #91909a
palette = 9 = #93000a
palette = 10 = #3b4279
palette = 11 = #5e3c54
palette = 12 = #444559
palette = 13 = #535a92
palette = 14 = #46464f
palette = 15 = #e4e1e9
background = #131318
foreground = #e4e1e9
cursor-color = #bcc2ff
cursor-text = #242b61
selection-background = #444559
selection-foreground = #e0e0f9
window-theme = ghostty
window-titlebar-background = #1f1f25
window-titlebar-foreground = #e4e1e9

