palette = 0 = #292a2f
palette = 1 = #ffb4ab
palette = 2 = #b6c4ff
palette = 3 = #e3bada
palette = 4 = #c2c5dd
palette = 5 = #dce1ff
palette = 6 = #dee1f9
palette = 7 = #c6c5d0
palette = 8 = #90909a
palette = 9 = #93000a
palette = 10 = #354479
palette = 11 = #5b3d57
palette = 12 = #424659
palette = 13 = #4d5c92
palette = 14 = #45464f
palette = 15 = #e3e1e9
background = #121318
foreground = #e3e1e9
cursor-color = #b6c4ff
cursor-text = #1e2d61
selection-background = #424659
selection-foreground = #dee1f9
window-theme = ghostty
window-titlebar-background = #1e1f25
window-titlebar-foreground = #e3e1e9

