palette = 0 = #262b27
palette = 1 = #ffb4ab
palette = 2 = #96d5a7
palette = 3 = #a2ceda
palette = 4 = #b6ccb9
palette = 5 = #b1f1c1
palette = 6 = #d2e8d4
palette = 7 = #c0c9bf
palette = 8 = #8b938a
palette = 9 = #93000a
palette = 10 = #11512e
palette = 11 = #214c57
palette = 12 = #384b3c
palette = 13 = #2e6a44
palette = 14 = #414942
palette = 15 = #dfe4dc
background = #101510
foreground = #dfe4dc
cursor-color = #96d5a7
cursor-text = #00391c
selection-background = #384b3c
selection-foreground = #d2e8d4
window-theme = ghostty
window-titlebar-background = #1c211c
window-titlebar-foreground = #dfe4dc

