source = ~/.config/matugen/generated/hyprlock-colors.conf

general {
    ignore_empty_input = true
    hide_cursor = true
}

background {
    monitor = 
    path = screenshot
    color = $color
    blur_size = 8
    blur_passes = 3
}

animations {
    enabled = true
}

input-field {
    monitor =
    size = 280, 50
    position = 0, 0
    halign = center
    valign = center

    inner_color = $inner_color
    outer_color = $outer_color
    outline_thickness = 0

    font_family = JetBrainsMono Nerd Font
    font_color = $font_color

    placeholder_text = Enter Password
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 8
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint {
        enabled = true
    }
}
