general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 600
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "off"})'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "on"})'
}

listener {
    timeout = 1200
    on-timeout = $XDG_CONFIG_HOME/scripts/hypridle-suspend.sh
}