[colors.primary]
background = '#121318'
foreground = '#e3e1e9'

[colors.cursor]
text = '#e3e1e9'
cursor = '#c6c5d0'

[colors.vi_mode_cursor]
text = '#121318'
cursor = '#b6c4ff'

[colors.search.matches]
foreground = '#45464f'
background = '#e3bada'

[colors.search.focused_match]
foreground = '#45464f'
background = '#b6c4ff'

[colors.footer_bar]
foreground = '#45464f'
background = '#e3e1e9'

[colors.hints.start]
foreground = '#45464f'
background = '#c2c5dd'

[colors.hints.end]
foreground = '#45464f'
background = '#c2c5dd'

[colors.selection]
text = '#121318'
background = '#b6c4ff'

[colors.normal]
black = '#292a2f'
red = '#ffb4ab'
green = '#b6c4ff'
yellow = '#e3bada'
blue = '#c2c5dd'
magenta = '#e3bada'
cyan = '#c2c5dd'
white = '#e3e1e9'

[colors.bright]
black = '#45464f'
red = '#93000a'
green = '#354479'
yellow = '#5b3d57'
blue = '#424659'
magenta = '#424659'
cyan = '#5b3d57'
white = '#c6c5d0'
