[colors.primary]
background = '#101510'
foreground = '#dfe4dc'

[colors.cursor]
text = '#dfe4dc'
cursor = '#c0c9bf'

[colors.vi_mode_cursor]
text = '#101510'
cursor = '#96d5a7'

[colors.search.matches]
foreground = '#414942'
background = '#a2ceda'

[colors.search.focused_match]
foreground = '#414942'
background = '#96d5a7'

[colors.footer_bar]
foreground = '#414942'
background = '#dfe4dc'

[colors.hints.start]
foreground = '#414942'
background = '#b6ccb9'

[colors.hints.end]
foreground = '#414942'
background = '#b6ccb9'

[colors.selection]
text = '#101510'
background = '#96d5a7'

[colors.normal]
black = '#262b27'
red = '#ffb4ab'
green = '#96d5a7'
yellow = '#a2ceda'
blue = '#b6ccb9'
magenta = '#a2ceda'
cyan = '#b6ccb9'
white = '#dfe4dc'

[colors.bright]
black = '#414942'
red = '#93000a'
green = '#11512e'
yellow = '#214c57'
blue = '#384b3c'
magenta = '#384b3c'
cyan = '#214c57'
white = '#c0c9bf'
