background #1a1110
foreground #f1dfdc
cursor #f1dfdc
cursor_text_color #1a1110
selection_background #5d3f3a
selection_foreground #ffdad4
url_color #dec48c
color0 #1a1110
color1 #ffb4ab
color2 #dec48c
color3 #e7bdb6
color4 #ffb4a8
color5 #dec48c
color6 #e7bdb6
color7 #f1dfdc
color8 #534341
color9 #93000a
color10 #564419
color11 #5d3f3a
color12 #73342a
color13 #5d3f3a
color14 #564419
color15 #d8c2be
active_tab_foreground #561e16
active_tab_background #ffb4a8
inactive_tab_foreground #ffdad4
inactive_tab_background #1a1110
