background #101510
foreground #dfe4dc
cursor #dfe4dc
cursor_text_color #101510
selection_background #384b3c
selection_foreground #d2e8d4
url_color #a2ceda
color0 #101510
color1 #ffb4ab
color2 #a2ceda
color3 #b6ccb9
color4 #96d5a7
color5 #a2ceda
color6 #b6ccb9
color7 #dfe4dc
color8 #414942
color9 #93000a
color10 #214c57
color11 #384b3c
color12 #11512e
color13 #384b3c
color14 #214c57
color15 #c0c9bf
active_tab_foreground #00391c
active_tab_background #96d5a7
inactive_tab_foreground #b1f1c1
inactive_tab_background #101510
