background #121318
foreground #e3e1e9
cursor #e3e1e9
cursor_text_color #121318
selection_background #424659
selection_foreground #dee1f9
url_color #e3bada
color0 #121318
color1 #ffb4ab
color2 #e3bada
color3 #c2c5dd
color4 #b6c4ff
color5 #e3bada
color6 #c2c5dd
color7 #e3e1e9
color8 #45464f
color9 #93000a
color10 #5b3d57
color11 #424659
color12 #354479
color13 #424659
color14 #5b3d57
color15 #c6c5d0
active_tab_foreground #1e2d61
active_tab_background #b6c4ff
inactive_tab_foreground #dce1ff
inactive_tab_background #121318
