font=JetBrainsMono Nerd Font 10
width=380
height=200
outer-margin=12,12
margin=8,8
padding=12
border-size=1
border-radius=0
default-timeout=3000
ignore-timeout=1
icons=1
max-icon-size=48
icon-location=left
icon-border-radius=0
markup=1
actions=1
text-alignment=left
anchor=top-right
layer=overlay
max-visible=5
history=1
max-history=15
sort=-time

background-color=#FFFFFFFF
text-color=#000000FF
border-color=#CCCCCCFF
progress-color=#000000FF

on-button-left=invoke-default-action
on-button-right=dismiss
on-button-middle=none
on-touch=dismiss

[urgency=critical]
default-timeout=0
ignore-timeout=0
border-color=#000000FF
