#!/usr/bin/env bash
# auto-generated by matugen from the current wallpaper
# sourced by grub-sync.sh to tint GRUB theme assets

GRUB_PRIMARY="{{colors.primary.default.hex_stripped}}"
GRUB_ON_PRIMARY="{{colors.on_primary.default.hex_stripped}}"
GRUB_SURFACE="{{colors.surface.default.hex_stripped}}"
GRUB_ON_SURFACE="{{colors.on_surface.default.hex_stripped}}"
GRUB_SURFACE_CONTAINER="{{colors.surface_container.default.hex_stripped}}"
