# Auto-generated by matugen — DO NOT EDIT MANUALLY
# Source: ~/.config/matugen/templates/grub-colors.sh
# Output: ~/.config/matugen/generated/grub-colors.sh
#
# Warna-warna ini berasal dari palette Material You wallpaper aktif,
# selaras dengan @primary / @on-primary yang dipakai rofi config.rasi.
#
# Format: HEX (tanpa '#'), siap dikonversi ke HSL oleh install.sh evodevo.
# install.sh akan memanggil hex_to_hsl() untuk masing-masing variabel ini.

# Selected item bar  →  sama dengan @primary (rofi: selected_item_background)
GRUB_FOCUS_HEX="{{colors.primary.default.hex_stripped}}"

# Teks & icon SAAT SELECTED  →  sama dengan @on-primary (rofi: selected_item_foreground)
GRUB_ON_PRIMARY_HEX="{{colors.on_primary.default.hex_stripped}}"

# Text warna normal  →  sama dengan @on-surface (rofi: normal-foreground)
GRUB_TEXT_HEX="{{colors.on_surface.default.hex_stripped}}"

# Icon warna         →  sama dengan @on-surface-variant (rofi: dimmed text)
GRUB_ICON_HEX="{{colors.on_surface_variant.default.hex_stripped}}"

# Background menu    →  sama dengan @surface-dim (rofi: window background base)
GRUB_MENU_HEX="{{colors.surface_dim.default.hex_stripped}}"

# Header background  →  sama dengan @surface-container (sedikit lebih terang)
GRUB_HEADER_HEX="{{colors.surface_container.default.hex_stripped}}"

# Progress bar bg    →  sama dengan @outline-variant (subtle)
GRUB_BAR_BG_HEX="{{colors.outline_variant.default.hex_stripped}}"

# Progress bar fg    →  sama dengan @primary (accent)
GRUB_BAR_FG_HEX="{{colors.primary.default.hex_stripped}}"
