$color = rgba({{colors.surface_container.default.hex_stripped}}ff)
$inner_color = rgba({{colors.surface_container_lowest.default.hex_stripped}}1a)
$outer_color = rgba({{colors.primary.default.hex_stripped}}ff)
$font_color = rgba({{colors.on_surface.default.hex_stripped}}ff)
$check_color = rgba({{colors.primary.default.hex_stripped}}ff)
$fail_color = rgba({{colors.error.default.hex_stripped}}ff)
